In [2]:
import torch 

In [115]:
x = torch.rand(3, 2, 3)  # Dimention, row , coloumn 
x

tensor([[[0.3361, 0.6099, 0.6221],
         [0.6999, 0.2249, 0.8707]],

        [[0.3838, 0.7852, 0.5925],
         [0.3054, 0.3927, 0.0113]],

        [[0.0594, 0.2737, 0.8685],
         [0.8663, 0.5591, 0.4828]]])

In [116]:

y = x.transpose(2, 1)
z = x.permute(1, 0,2) 


print (y.shape, z.shape)
print (y)
print (z)

torch.Size([3, 3, 2]) torch.Size([2, 3, 3])
tensor([[[0.3361, 0.6999],
         [0.6099, 0.2249],
         [0.6221, 0.8707]],

        [[0.3838, 0.3054],
         [0.7852, 0.3927],
         [0.5925, 0.0113]],

        [[0.0594, 0.8663],
         [0.2737, 0.5591],
         [0.8685, 0.4828]]])
tensor([[[0.3361, 0.6099, 0.6221],
         [0.3838, 0.7852, 0.5925],
         [0.0594, 0.2737, 0.8685]],

        [[0.6999, 0.2249, 0.8707],
         [0.3054, 0.3927, 0.0113],
         [0.8663, 0.5591, 0.4828]]])


In [73]:
x = torch.rand(1, 2, 3)

print(x,x.shape)

x = x.permute(1, 2, 0)
print(x.shape)

tensor([[[0.1591, 0.2908, 0.4526],
         [0.5065, 0.0894, 0.6569]]]) torch.Size([1, 2, 3])
torch.Size([2, 3, 1])


In [35]:
z=x.permute(2, 1, 0)


tensor([[[0.9252, 0.2700, 0.4553, 0.9693],
         [0.1631, 0.0742, 0.3437, 0.7508]],

        [[0.7282, 0.8300, 0.1608, 0.9449],
         [0.5755, 0.7139, 0.8793, 0.0987]],

        [[0.0903, 0.9128, 0.1692, 0.2425],
         [0.6054, 0.0731, 0.3013, 0.7516]]])

In [110]:
x = torch.randn(2, 3, 5)
print(x)
print( x.size() )

y=x.permute(2, 0, 1) 

# index be changed after permute 
#After permute  [ dimension=> x_index[2]=5 ],  [ Row => x_index[0]=2 ], [ Column=> x_index[1]=3 ]

print( y.size() )
print(y)

tensor([[[-0.5343, -0.0598,  0.5498,  1.4276, -0.5987],
         [ 0.2402,  0.4135,  0.4999,  1.3838, -1.2628],
         [ 0.0907,  0.0809, -1.2053,  0.7666, -0.6444]],

        [[ 0.7903,  1.1829, -0.5667, -0.0142, -0.4898],
         [-0.2596, -3.0139, -0.6189, -1.5202, -1.6454],
         [ 0.9513, -0.6368,  0.6926,  0.7991,  1.2432]]])
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[[-0.5343,  0.2402,  0.0907],
         [ 0.7903, -0.2596,  0.9513]],

        [[-0.0598,  0.4135,  0.0809],
         [ 1.1829, -3.0139, -0.6368]],

        [[ 0.5498,  0.4999, -1.2053],
         [-0.5667, -0.6189,  0.6926]],

        [[ 1.4276,  1.3838,  0.7666],
         [-0.0142, -1.5202,  0.7991]],

        [[-0.5987, -1.2628, -0.6444],
         [-0.4898, -1.6454,  1.2432]]])
