In [1]:
import numpy as np

X = np.array([
[0, 0, 1],
[0, 1, 1],
[1, 0, 1],
[1, 1, 1]])
y = np.array([[0],
              [1],
              [1],
              [0]])
              
#Weight Initialize             
w1=np.random.random((3,2))
w2=np.random.random((2,1))

#sigmoid function   
def sigmoid(x, deriv=False):
  if(deriv):
    return x*(1-x)
  else:
    return (1/(1+np.exp(-x)))
 


In [2]:
#Back propagation   
for epoch in range(0,30000):

  eta=0.5
  #Weighted Sum

  z_h=np.dot(X,w1)
  a_h=sigmoid(z_h)
  
  # second weighted sum
  z_o=np.dot(a_h,w2)
  a_o=sigmoid(z_o)
    
  #Error Calculate
  Ea=(0.5*(np.power((a_o-y),2)))
    
  #BackPropagation dE/dw2
  #dE/da0
  dEda0=(a_o-y)

  #da0/dz0
  da0dz0=sigmoid(a_o,deriv=True)

  #dz0/dw
  dz0dw=a_h

  #dE/dw2
  st=da0dz0*dEda0
  dEdw2=np.dot(dz0dw.T,st)
    
  #Weight update
  w2=w2-(eta*dEdw2)
    
  #hidden Layer dEdw1
  #dE/dah
  dEdah=np.dot(st,w2.T)

  #dzh/dw
  dzhdw=X

  #dah/dzh
  dahdzh=sigmoid(a_h,deriv=True)
  fs=dEdah*dahdzh
  dEdw1=np.dot(dzhdw.T,fs)

  #Weight Update
  w1=w1-(eta*dEdw1)
 


In [3]:
print(w1)
print(w2)

#testing final output
test_a_h=sigmoid(np.dot(X,w1));
prediction=sigmoid(np.dot(test_a_h,w2))
print(prediction)

[[10.63253703  9.90219851]
 [ 5.41474554 -2.81078433]
 [-1.23518494  2.09209527]]
[[ 7.21410275]
 [-7.21409544]]
[[0.00819224]
 [0.9913493 ]
 [0.4998634 ]
 [0.5001864 ]]
